/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import com.sun.net.httpserver.HttpServer;
import java.net.InetSocketAddress;

public class App {
    public static void main(String[] args) throws Exception {
        // サーバをポート8080で作成
        HttpServer server = HttpServer.create(new InetSocketAddress(8080), 0);

        // エンドポイントを登録
        server.createContext("/", new HelloHandler()); // http://localhost:8080/
        server.createContext("/custom", new CustomHandler()); // http://localhost:8080/custom

        // サーバを開始
        server.setExecutor(null); // デフォルトのスレッドプール
        server.start();
        System.out.println("Server started on http://localhost:8080");
    }
}
